```{r}
library(tidyverse)
```

```{r}
realfootball<- read_csv("EPLredcard_data.csv")
```

```{r}
realfootball %>% 
  group_by(`Time of Red Cards Given`, WLT) %>%
  summarise(
    total = n())%>% 
  arrange(`Time of Red Cards Given`)
  
```

```{r}
RCD <- realfootball %>%
  group_by(`Time of Red Cards Given`, WLT)%>%
  summarise(
    total = n())
RCD
```
```{r}
RCD %>% 
  separate(`Time of Red Cards Given`, into=c("RegularTime", "AddedTime"), sep="\\+") %>% 
  mutate_all(funs(ifelse(is.na(.), 0, .))) %>% 
  mutate(
    `RegularTime` = as.numeric(gsub("'", "", `RegularTime`, fixed=TRUE)),
    `AddedTime`   = as.numeric(gsub("'", "", `AddedTime`, fixed=TRUE)),
    total_time = `RegularTime` + `AddedTime`
    ) %>% 
  mutate(
    game_section = case_when(
      RegularTime <= 15  ~ "1-15",
      RegularTime >= 16 & RegularTime <= 30 ~ "16-30",
      RegularTime >= 31 & RegularTime <= 45~ "31-45",
      RegularTime >= 46 & RegularTime <= 60~ "46-60",
      RegularTime >= 61 & RegularTime <= 75 ~ "61-75",
      RegularTime >= 76 & RegularTime <= 90 ~ "76-90",
      TRUE ~ as.character(total_time)
      ) 
  ) -> footballredcards

```

```{r}
ggplot(footballredcards, aes(x=game_section, weight=total, fill=WLT)) + 
  geom_bar() +
  labs(
    title="Results based on Timing of Red Cards in the Premier League", 
    x="Minute of Red Card Given", 
    y="Amount of Red Cards Given") +
  theme_minimal()+
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 12), 
    plot.subtitle = element_text(size=12), 
    panel.grid.minor = element_blank()
    )
```

```{r}
ggplot() + geom_bar(data=footballredcards, aes(x=game_section, weight=total, fill=WLT)) + theme_minimal() + coord_polar()+
  labs(
    title="Results based on Timing of Red Cards in the Premier League", 
    x="Minute of Red Card Given", 
    y="Amount of Red Cards Given") +
  theme_minimal()+
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 12), 
    plot.subtitle = element_text(size=12), 
    panel.grid.minor = element_blank()
    )
```

